### ISSUE TITLE
I'm getting this in the last step

### ISSUE THREAD

**Issue by Raavan-hash** [noob-hackers/infect#1]
infect.sh: line 98: cd: /data/data/com.termux/files/home/infect/lol: No such file or directory

**Comment by noob-hackers** [comment]
makesure you didnt deleted any dir

**Comment by Matt-Hatter20** [comment]
Same

**Comment by babu0000000** [comment]
Same

**Comment by ItsAlex42** [comment]
Replace line with `cd lol`.
you can use nano for editing infect.sh
