### ISSUE TITLE
My analysis about this tool && A stuff that I just wanna share with you guyz.

### ISSUE THREAD

**Issue by ZechBron** [noob-hackers/infect#20]
## This Tool
+ I've checked and run this tool myself. And I've noticed something:
   But First of all. Good Work to @noob-hackers I didn't encounter issue. It works.

   What I did is I copied the link:

   ![Screenshot_20200930_011633](https://user-images.githubusercontent.com/39665654/94640448-59273080-0311-11eb-9a6f-bb190e7ee5be.png)

   Which is sorted using bitly. So I've tried to expand it. And this is the output. 
   ![Screenshot_20200930_011652](https://user-images.githubusercontent.com/39665654/94640425-47de2400-0311-11eb-8971-736e44d96bad.png)

   The link is a real virus. __Elite apk Virus__ to be exact. Which is taken from a raw file of  harshalbenake. 

+ Now guyz, I've created exact similar to this tool `and VCRT`. Kinda similar. Well __infect__ uses link so all you have to do is to send the link to your victim and let the victim download it. Same with the script of mine which is __Z Virus__

   You can visit it here: https://github.com/ZechBron/zVirus-Gen

**Comment by noob-hackers** [comment]
Thanks for suggesting ♥️
