### ISSUE TITLE
facsimile!!!!

### ISSUE THREAD

**Issue by Bhaviktutorials** [noob-hackers/Infect#26]

**Comment by noob-hackers** [comment]
Sure, a collaboration could be a good idea
Don't worry we wont let your hard work go worthless....we will credit you
in readme.md

Thanks for your feedback
🤗Regards Noob Hackers

**Comment by noob-hackers** [comment]
Hope You Are Happy Now 😇

**Comment by noob-hackers** [comment]
oh bhavik sry ...one of my frnd gave it to me ...🙏 Sure will credit you in
readme.md ...dotn worry

Thanks for informing
