### ISSUE TITLE
How does the payload hosting page look?

### ISSUE THREAD

**Issue by minanagehsalalma** [noob-hackers/infect#3]

**Comment by minanagehsalalma** [comment]
@noob-hackers lol noob the link downloads your static payload.

Reported as malicious.

**Comment by noob-hackers** [comment]
@minanagehsalama lol don't be stupid, it's not payload 😂😂😂 it's virus app, even you don't know the meaning of payload come on bro ✌️😂😂😎

**Comment by minanagehsalalma** [comment]
> it's virus app, even you don't know the meaning of payload come on bro ✌️😂😂😎

Well i didn't run it ... but that kinda mean to trick them into sharing your "virus app" to others and call it for educational purposes.
